# Generated by Django 5.2.13 on 2026-04-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.items.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "identificador",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("asignado", "Asignado"),
                            ("en_revision", "En revisión"),
                            ("documentado", "Documentado"),
                        ],
                        default="libre",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="última modificación"),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario asignado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="catalog.tipo",
                        verbose_name="tipo",
                    ),
                ),
                (
                    "vitrina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="catalog.vitrina",
                        verbose_name="vitrina",
                    ),
                ),
            ],
            options={
                "verbose_name": "pieza",
                "verbose_name_plural": "piezas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ItemPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.items.models._photo_upload_path,
                        verbose_name="imagen",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de subida"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="items.item",
                        verbose_name="pieza",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="subida por",
                    ),
                ),
            ],
            options={
                "verbose_name": "foto",
                "verbose_name_plural": "fotos",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["estado"], name="items_item_estado_9f97cd_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["assigned_user"], name="items_item_assigne_d1eae5_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["tipo"], name="items_item_tipo_id_3b67b7_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["vitrina"], name="items_item_vitrina_73830e_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["activo"], name="items_item_activo_f5d069_idx"),
        ),
    ]
