# Generated by Django 5.2.13 on 2026-04-17 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_auto_identificador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="identificador",
        ),
    ]
