# Generated by Django 5.2.13 on 2026-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_remove_identificador"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="URL"
            ),
        ),
    ]
