# Generated by Django 5.2.13 on 2026-04-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_add_url_to_vitrina"),
        ("items", "0004_add_url_to_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tipos",
            field=models.ManyToManyField(
                blank=True,
                related_name="typed_items",
                to="catalog.tipo",
                verbose_name="tipos",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="catalog.tipo",
                verbose_name="tipo",
            ),
        ),
    ]
