# Generated by Django 5.2.13 on 2026-04-17 12:16

from django.db import migrations


def copy_tipo_to_tipos(apps, schema_editor):
    Item = apps.get_model("items", "Item")
    for item in Item.objects.filter(tipo__isnull=False):
        item.tipos.add(item.tipo)


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_add_tipos_m2m"),
    ]

    operations = [
        migrations.RunPython(copy_tipo_to_tipos, migrations.RunPython.noop),
    ]
