# Generated by Django 5.2.13 on 2026-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_add_url_to_vitrina"),
        ("items", "0006_copy_tipo_to_tipos"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="item",
            name="items_item_tipo_id_3b67b7_idx",
        ),
        migrations.RemoveField(
            model_name="item",
            name="tipo",
        ),
        migrations.AlterField(
            model_name="item",
            name="tipos",
            field=models.ManyToManyField(
                blank=True,
                related_name="items",
                to="catalog.tipo",
                verbose_name="tipos",
            ),
        ),
    ]
