# Generated by Django 5.2.13 on 2026-04-25 16:27

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_numero"),
        ("items", "0007_remove_tipo_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="vitrina_slot",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9A-F]$",
                        "Introduce un carácter hexadecimal válido (0-9 o A-F).",
                    )
                ],
                verbose_name="slot en vitrina",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("vitrina__isnull", False),
                    models.Q(("vitrina_slot", ""), _negated=True),
                ),
                fields=("vitrina", "vitrina_slot"),
                name="unique_item_vitrina_slot",
            ),
        ),
    ]
