services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: museoman
      POSTGRES_PASSWORD: museoman
      POSTGRES_DB: museoman
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - museoman_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U museoman -d museoman"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    restart: unless-stopped
    environment:
      # URL_PATH: "/museo"
      # USE_X_FORWARDED_HOST: False
      # CSRF_TRUSTED_ORIGINS:
      SECRET_KEY: cambia-esta-clave-en-produccion
      DEBUG: "False"
      ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: postgresql://museoman:museoman@db:5432/museoman
      DISCORD_WEBHOOK_URL: ""
      MEDIA_ROOT: /app/media
      STATIC_ROOT: /app/staticfiles
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
    networks:
      - museoman_net
    depends_on:
      db:
        condition: service_healthy

networks:
  museoman_net:

volumes:
  postgres_data:
  media_data:
