# Generated by Django 5.2.13 on 2026-04-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("state_change", "Cambio de estado"),
                            ("assigned", "Asignación"),
                            ("deactivated", "Desactivación"),
                            ("activated", "Activación"),
                            ("photo_added", "Foto añadida"),
                            ("photo_deleted", "Foto eliminada"),
                        ],
                        max_length=30,
                        verbose_name="acción",
                    ),
                ),
                (
                    "from_state",
                    models.CharField(blank=True, max_length=30, verbose_name="estado anterior"),
                ),
                (
                    "to_state",
                    models.CharField(blank=True, max_length=30, verbose_name="estado nuevo"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="datos"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="items.item",
                        verbose_name="pieza",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "-created_at"],
                        name="audit_audit_item_id_ff68ba_idx",
                    )
                ],
            },
        ),
    ]
