# Generated by Django 5.2.13 on 2026-04-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        ("catalog", "0004_remove_numero"),
        ("items", "0007_remove_tipo_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="vitrina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="catalog.vitrina",
                verbose_name="vitrina",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("state_change", "Cambio de estado"),
                    ("assigned", "Asignación"),
                    ("deactivated", "Desactivación"),
                    ("activated", "Activación"),
                    ("photo_added", "Foto añadida"),
                    ("photo_deleted", "Foto eliminada"),
                    ("created", "Creación"),
                    ("updated", "Edición"),
                    ("vitrina_created", "Vitrina creada"),
                    ("vitrina_updated", "Vitrina editada"),
                    ("vitrina_deleted", "Vitrina eliminada"),
                ],
                max_length=30,
                verbose_name="acción",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="items.item",
                verbose_name="pieza",
            ),
        ),
    ]
