# Generated by Django 5.2.13 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_add_item_vitrina_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="field",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="campo"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="from_state",
            field=models.CharField(blank=True, max_length=255, verbose_name="valor anterior"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="to_state",
            field=models.CharField(blank=True, max_length=255, verbose_name="valor nuevo"),
        ),
    ]
