# Generated by Django 5.2.13 on 2026-04-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_vitrina_add_nombre_auto_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitrina",
            name="url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="URL"
            ),
        ),
    ]
