# Generated by Django 5.2.13 on 2026-04-17 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_add_url_to_vitrina"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vitrina",
            options={
                "ordering": ["pk"],
                "verbose_name": "vitrina",
                "verbose_name_plural": "vitrinas",
            },
        ),
        migrations.RemoveField(
            model_name="vitrina",
            name="numero",
        ),
    ]
